### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by luodanwg** [mermaidjs/mermaid-live-editor#13]
with the lastest version ,when i build on it , occurs below error. help help.

PS E:\Git\mermaid-live-editor> yarn dev
yarn dev v1.0.2
$ node -r babel-register node_modules/.bin/webpack-dev-server
E:\Git\mermaid-live-editor\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Git\mermaid-live-editor\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tylerlong** [comment]
I think you are using Windows.

Please try again and let me know if you still have this issue.
