### ISSUE TITLE
yarn dev exploding

### ISSUE THREAD

**Issue by Heiko-san** [mermaidjs/mermaid-live-editor#71]
I'm triying to run `yarn dev` under arch linux, it actually used to work but since an update stopped working with the following error:

```
yarn run v1.19.1
$ parcel ./index.html -d build
(node:30498) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/build/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/build/Debug/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/build/Release/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/out/Debug/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/Debug/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/out/Release/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/Release/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/build/default/deasync.node
 → /files/git/privat/mermaid-live-editor/node_modules/deasync/compiled/13.1.0/linux/x64/deasync.node
    at bindings (/files/git/privat/mermaid-live-editor/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/files/git/privat/mermaid-live-editor/node_modules/deasync/index.js:30:31)
    at Module._compile (/files/git/privat/mermaid-live-editor/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (/files/git/privat/mermaid-live-editor/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/files/git/privat/mermaid-live-editor/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/files/git/privat/mermaid-live-editor/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
(node:30498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.24s.
```

I don't really have a clue about nodejs stuff so please help me what could cause this.

**Comment by Heiko-san** [comment]
No idea?

if info is missing tell me which and I will provide it.
